<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH01_04_Artificial_Neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1-3:Activation Functions**#

##**Code1-3-1:Activation Layers**##

In [6]:
# activation fucn만 만드는 법

import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5))  #input setting 

# imp. activation function

sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(Tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(manual)     ,  실제 연산

y_sigmoid_man  = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(0,x)

print("x : {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(manual): {}\n{}".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(manual): {}\n{}".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLU(Tensorflow): {}\n{}".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLU(manual): {}\n{}".format(y_relu_man.shape, y_relu_man.numpy()))

x : (1, 5)
[[ 1.807891    1.2539947  -0.93710077 -0.13290061 -0.48402297]]
Sigmoid(Tensorflow): (1, 5)
[[0.8591068  0.7779906  0.28148636 0.46682367 0.3813026 ]]
Sigmoid(manual): (1, 5)
[[0.8591068  0.7779906  0.28148636 0.46682364 0.38130262]]
Tanh(Tensorflow): (1, 5)
[[ 0.9476171   0.84940004 -0.7338874  -0.13212363 -0.4494597 ]]
Tanh(manual): (1, 5)
[[ 0.9476172   0.84940004 -0.7338874  -0.13212363 -0.4494597 ]]
ReLU(Tensorflow): (1, 5)
[[1.807891  1.2539947 0.        0.        0.       ]]
ReLU(manual): (1, 5)
[[1.807891  1.2539947 0.        0.        0.       ]]


##**Code1-3-2:Activation in Dense Layer**##

In [18]:
# Dense Layer안에 activation function 구현하기

import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1,5))  #input setting 

# imp. artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid')  # affine + activation
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagation(Tensorflow)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

# print resluts
print("AN with Sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with ReLU: {}\n{}".format(y_relu.shape, y_relu.numpy()))

# forward propagation(manual)
print('\n====\n')

W_sigmoid, B_sigmoid = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x,W_sigmoid) + B_sigmoid
a_sigmoid  = 1 / (1 + exp(-z))
print("Activation Sigmoid value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation Sigmoid value(manual): {}\n{}".format(a_sigmoid.shape, a_sigmoid.numpy()))

W_tanh, B_tanh = dense_tanh.get_weights()
z_tanh = tf.linalg.matmul(x,W_tanh) + B_tanh
a_tanh  = (exp(z_tanh) - exp(-z_tanh)) / (exp(z_tanh) + exp(-z_tanh))
print("Activation Tanh value(Tensorflow): {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("Activation Tanh value(manual): {}\n{}".format(a_tanh.shape, a_tanh.numpy()))

W_relu, B_relu = dense_relu.get_weights()
z_relu = tf.linalg.matmul(x,W_relu) + B_relu
a_relu  = maximum(0,z_relu)
print("Activation ReLU value(Tensorflow): {}\n{}".format(y_relu.shape, y_relu.numpy()))
print("Activation ReLU value(manual): {}\n{}".format(a_relu.shape, a_relu.numpy()))


AN with Sigmoid: (1, 1)
[[0.48862118]]
AN with Tanh: (1, 1)
[[-0.06860781]]
AN with ReLU: (1, 1)
[[0.]]

====

Activation Sigmoid value(Tensorflow): (1, 1)
[[0.48862118]]
Activation Sigmoid value(manual): (1, 1)
[[0.48862115]]
Activation Tanh value(Tensorflow): (1, 1)
[[-0.06860781]]
Activation Tanh value(manual): (1, 1)
[[-0.0686078]]
Activation ReLU value(Tensorflow): (1, 1)
[[0.]]
Activation ReLU value(manual): (1, 1)
[[0.]]


#**1-4:Artificial Neurons**#

##**Code1-4-1: Artificial Neurons**##

In [28]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

#activation = 'sigmoid'
#activation = 'tanh'
activation = 'relu'

#input setting
x = tf.random.uniform(shape=(1,10))

dense = Dense(units=1, activation=activation)  #imp. an affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

#calculate activation value manually
y_man = tf.linalg.matmul(x,W) + B
if activation == 'sigmoid' :
  y_man = 1 / (1 + exp(-y_man))
elif activation == 'tanh' :
  y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))
elif activation == 'relu' :
  y_man = maximum(0,y_man)

print("Activation: ", activation)
print("y_tf: {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y_man: {}\n{}\n".format(y_man.shape, y_man.numpy()))

Activation:  relu
y_tf: (1, 1)
[[0.48963225]]

y_man: (1, 1)
[[0.48963225]]



#**1-5:MiniBatches**#

##**Code1-5-1: Shapes of Dense Layers**##

In [30]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# set input params
N, n_feature = 8, 10
# generate minibatch
x = tf.random.normal(shape=(N, n_feature))  # matrix형태, 8행10열

# imp. an AN
dense = Dense(units=1,activation='relu')
#forward propagation
y = dense(x)

# get weight/bias
W, B = dense.get_weights()

#print results
print("Shape of x: {}", x.shape)
print("Shape of W: {}", W.shape)
print("Shape of B: {}", B.shape)

Shape of x: {} (8, 10)
Shape of W: {} (10, 1)
Shape of B: {} (1,)


##**Code1-5-2: Output Calculations**##

In [35]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

# set input params
N, n_feature = 8, 10
# generate minibatch
x = tf.random.normal(shape=(N, n_feature))  # matrix형태, 8행10열

# imp. an AN
dense = Dense(units=1,activation='sigmoid')
#forward propagation(Tensorflow)
y_tf = dense(x)

W, B = dense.get_weights()

#forward propagation(Tensorflow)
y_man = tf.linalg.matmul(x,W) + B
y_man = 1 / (1 + tf.math.exp(-y_man))
# print results
print("Output(Tensorflow): \n", y_tf.numpy())
print("Output(manual): \n", y_man.numpy())
#print(tf.math.equal(y_tf, y_man))  # floating point가 잘려 나와 항상 True가 아니다


Output(Tensorflow): 
 [[0.48920912]
 [0.57421196]
 [0.47956005]
 [0.5983009 ]
 [0.5136241 ]
 [0.35580188]
 [0.7624293 ]
 [0.80499876]]
Output(manual): 
 [[0.48920915]
 [0.574212  ]
 [0.47956005]
 [0.5983009 ]
 [0.5136241 ]
 [0.35580185]
 [0.76242924]
 [0.80499876]]
