<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH02_05_06_Dense_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**2-1: Dense Layers**#

##**Code2-1-1: Shapes of Dense Layers**##

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N,n_feature = 8, 10 
X = tf.random.normal(shape=(N, n_feature))  # input setting, N행 n_feature열인 X matrix

n_neuron = 3 # neuron의 갯수
dense = Dense(units = n_neuron, activation = 'sigmoid')  # 뉴런이 3개인 dense layer -> weight vector 3X10, bias vector 1X3
Y = dense(X) 

W, B = dense.get_weights()

print('==== Input/Weight/Output====')
print("X: ",X.shape)
print("W: ",W.shape)
print("B: ",B.shape)
print("Y: ",Y.shape)

print(W)

==== Input/Weight/Output====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)
[[ 0.13532078 -0.28365242  0.17590165]
 [-0.12819493 -0.29023793  0.18400097]
 [ 0.54652643 -0.44886494 -0.6654114 ]
 [ 0.46448863  0.10888106  0.18547446]
 [-0.08024979 -0.27139023  0.6523154 ]
 [-0.04271567 -0.63102084 -0.4830041 ]
 [-0.137084    0.15628451  0.17295855]
 [ 0.3982631  -0.36900857 -0.1139639 ]
 [ 0.6428019  -0.10790271  0.20670998]
 [ 0.19415426  0.6031543  -0.35858965]]


##**Code2-1-2: Output Calculation**##

In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N,n_feature = 4, 10 
X = tf.random.normal(shape=(N, n_feature))  # input setting, N행 n_feature열인 X matrix

n_neuron = 3 # neuron의 갯수
dense = Dense(units = n_neuron, activation = 'sigmoid')  # 뉴런이 3개인 dense layer -> weight vector 3X10, bias vector 1X3
Y_tf = dense(X) 

W, B = dense.get_weights()

print("Y(Tensorflow): \n",Y_tf.numpy())

#calculate matrix multiplication
z = matmul(X,W) + B
Y_man_matmul = 1 / (1 + exp(-z))
print("Y(with matrix multiplication): \n",Y_man_matmul.numpy())

#calculate with dot products
Y_man_vec = np.zeros(shape=(N,n_neuron))   # array안에 값을 바꾸기 위해 numpy가져옴, N by n_neuron zero matrix
for x_idx in range (N):
  x = X[x_idx]  #하나의 datasample씩 뽑아온다 -> x matrix의 행마다 반복

  for nu_idx in range (n_neuron) : # 뉴런 갯수마다 반복
    w, b = W[:, nu_idx], B[nu_idx]  # weight vector 하나씩 가져옴, bias vector 하나씩

    z = tf.reduce_sum(x * w) + b
    a = 1 / (1 + np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot product): \n", Y_man_vec) 

Y(Tensorflow): 
 [[0.31730202 0.87344545 0.11364233]
 [0.61902356 0.28036708 0.34578484]
 [0.04225206 0.52872413 0.36816335]
 [0.57957554 0.09428012 0.84301865]]
Y(with matrix multiplication): 
 [[0.31730202 0.8734455  0.11364236]
 [0.6190236  0.28036708 0.3457848 ]
 [0.0422521  0.52872413 0.36816332]
 [0.5795756  0.09428016 0.84301865]]
Y(with dot product): 
 [[0.31730202 0.87344545 0.11364235]
 [0.6190236  0.28036709 0.34578481]
 [0.0422521  0.52872411 0.36816333]
 [0.57957554 0.09428016 0.84301864]]


#**Cascaded Dense Layers**#



##**Code2-2-1: Shapes of cascaded Dense Layers**##

In [11]:
# 여러개의 dense layer만들기

import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10  # N = minibatch size
X = tf.random.normal(shape=(N, n_feature))  # 4 by 10 행렬

n_neurons = [3,5]
dense1 = Dense(units = n_neurons[0], activation = 'sigmoid')  # 뉴런 3개
dense2 = Dense(units = n_neurons[1], activation = 'sigmoid')  # 뉴런 5개
#dense3 = Dense(units = n_neurons[2], activation = 'sigmoid')

#forward propagation
A1 = dense1(X)  # W1 10 by 3, B1 1 by 3, A1 4 by 3
Y = dense2(A1)  # W2 3 by 5, B2 1 by 5, Y 4 by 5

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X : {}\n".format(X.shape))
print("W1 : ",W1.shape)
print("B1 : ",B1.shape)
print("A1 : {}\n".format(A1.shape))
print("W2 : ",W2.shape)
print("B2 : ",B2.shape)
print("Y : {}\n".format(Y.shape))

X : (4, 10)

W1 :  (10, 3)
B1 :  (3,)
A1 : (4, 3)

W2 :  (3, 5)
B2 :  (5,)
Y : (4, 5)



##**Code2-2-2: Dense Layers with Python List**##

In [17]:
# 여러개의 리스트를 만들고 통과시켜주기
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10  # N = minibatch size
X = tf.random.normal(shape=(N, n_feature))  # 4 by 10 행렬

n_neurons = [10, 20 ,30, 40 ,50, 60, 70, 80, 90, 100]

# 레이어를 하나씩 적어주지않고 리스트로 만들어 계산
dense_layers = list()  
for n_neuron in n_neurons :
  dense = Dense(units = n_neuron, activation= 'relu')
  dense_layers.append(dense)
  
print("Input: ",X.shape)
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print("After dense layer ", dense_idx)
  print(X.shape, '\n')
Y = X


Input:  (4, 10)
After dense layer  0
(4, 10) 

After dense layer  1
(4, 20) 

After dense layer  2
(4, 30) 

After dense layer  3
(4, 40) 

After dense layer  4
(4, 50) 

After dense layer  5
(4, 60) 

After dense layer  6
(4, 70) 

After dense layer  7
(4, 80) 

After dense layer  8
(4, 90) 

After dense layer  9
(4, 100) 



##**Code2-2-3: Output Calculations**##

In [22]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10  # N = minibatch size
X = tf.random.normal(shape=(N, n_feature))  # 4 by 10 행렬
X_cp = tf.identity(X)  # X값 copy -> 아래의 forward propagation(matmul)에서 쓰기위해, X와 서로 다른 위치에 저장해줌

n_neurons = [3, 4, 5]

# 레이어를 하나씩 적어주지않고 리스트로 만들어 계산
dense_layers = list()  

for n_neuron in n_neurons :
  dense = Dense(units = n_neuron, activation= 'sigmoid')
  dense_layers.append(dense)
  
# forward propagation(Tensroflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)
print("Y(Tensorflow): ",X.numpy())

# forward propagation(manual)
for layer_idx in range(len(n_neurons)) :
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp, w) + b
  X_cp = 1 / (1 + exp(-X_cp))
print("Y(manual): ",X_cp.numpy())


Y(Tensorflow):  [[0.5447289  0.52328324 0.51502806 0.40427852 0.36841965]
 [0.5376273  0.512421   0.51000047 0.41789758 0.37940234]
 [0.54138696 0.5183738  0.51110613 0.40832704 0.37313628]
 [0.5469292  0.51807094 0.5244932  0.39966416 0.36672288]]
Y(manual):  [[0.5447289  0.52328324 0.51502806 0.40427852 0.36841968]
 [0.5376273  0.512421   0.51000047 0.41789758 0.3794023 ]
 [0.54138696 0.5183738  0.51110613 0.408327   0.37313628]
 [0.5469292  0.51807094 0.5244932  0.39966413 0.36672285]]
