<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH03_04_%5B%EA%B5%AC%ED%98%84%EA%B0%95%EC%9D%98%5D_Multiclass_Classifiers_ipynb_%5B%EA%B5%AC%ED%98%84%EA%B0%95%EC%9D%98%5D_Multiclass_Classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**3-4: Softmax Layers**#

##**Code3-4-1: IO of Softmax**##

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)  # 열 기준 계산

print("Logits: \n",logit.numpy())
print("Probabilities : \n", softmax_value.numpy())
print("Sum of softmax values: \n", softmax_sum)  # sum = 1이여야함

Logits: 
 [[-1.916687   -5.733509    3.7484627  -7.279396   -4.2998385 ]
 [-9.271793    8.50437     1.3734322   8.120691    2.5568504 ]
 [-6.518402   -8.907463   -1.1298084  -9.354267   -3.547089  ]
 [-5.0065923   1.9698887  -2.3188806   8.167702    3.2706976 ]
 [ 2.5599842   0.04105759 -5.241158   -0.03053665 -1.3174458 ]
 [-3.8684416   6.427862   -5.7993507  -8.006101    4.8766327 ]
 [ 1.5249968  -1.7952442   0.8241539  -0.648551    1.1239719 ]
 [ 1.5017242   3.2117252   3.6775284  -4.457059   -6.321852  ]]
Probabilities : 
 [[3.4512498e-03 7.5919204e-05 9.9613827e-01 1.6180109e-05 3.1840993e-04]
 [1.1307632e-08 5.9355533e-01 4.7482588e-04 4.0441921e-01 1.5505522e-03]
 [4.1742632e-03 3.8284578e-04 9.1372675e-01 2.4489468e-04 8.1471302e-02]
 [1.8808609e-06 2.0146689e-03 2.7644903e-05 9.9055743e-01 7.3984000e-03]
 [8.4987754e-01 6.8454251e-02 3.4782704e-04 6.3724644e-02 1.7595837e-02]
 [2.7852233e-05 8.2506454e-01 4.0390278e-06 4.4452636e-07 1.7490311e-01]
 [4.3183157e-01 1.5608173e-02

##**Code3-4-2: Softmax in Dense Layers**##

In [ ]:
from os import access
import tensorflow as tf

from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
dense = Dense(units=8, activation='softmax')

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[0.9999999  0.9999999  1.         1.         1.         0.99999994
 1.         1.        ], shape=(8,), dtype=float32)


#**3-5: Multi-class Classifiers**#

##**Code3-5-1: Multi-class Classifiers**##

In [ ]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=8, activaiton='relu')
    self.dense2 = Dense(units=5, activaiton='relu')
    self.dense3 = Dense(units=3, activaiton='softmax')

  def call(self, x):
    print("X : {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense1(x)
    print("A1: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense2(x)
    print("A2: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense3(x)
    print("Y: {}\n{}\n".format(x.shape, x.numpy()))
    print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
    return x

model = TestModel()

X = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
Y = model(X)

TypeError: ignored

In [ ]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

class TestModel (Model):
  def __init (self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=8, actvation='relu')
    self.dense2 = Dense(units=5, actvation='relu')
    self.dense3 = Dense(units=3, actvation='softmax')

  def call(self, x):
    print("X: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense1(x)
    print("A1: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense2(x)
    print("A2: {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense3(x)
    print("Y: {}\n{}\n".format(x.shape, x.numpy()))
    print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
    return x

model = TestModel()

X = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
Y = model(X)

X: (8, 5)
[[ 5.0329304   2.6557846   1.0142326   7.417448    7.1534443 ]
 [ 5.098789    3.9628792   1.7300177   6.6642094   0.05438995]
 [ 7.2290974   0.96699905 -0.9412937  -3.6288714   8.976992  ]
 [-9.405489   -6.7602515   1.4018583  -0.48942375 -1.7755585 ]
 [-6.041503   -8.040131   -2.0764709   9.9401245  -4.392669  ]
 [-8.322456    3.9066267   3.6023693  -6.83892     8.521498  ]
 [-1.0286999   8.061348    8.55909    -0.86731434 -8.4512615 ]
 [ 1.740839   -9.046343   -5.899935   -9.163098   -5.2475953 ]]



AttributeError: ignored