<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH03_04__Multiclass_Classifiers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**3-4: Softmax Layers**#

##**Code3-4-1: IO of Softmax**##

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
softmax_value = Activation('softmax')(logit)
# axis = 1 -> 열
softmax_sum = tf.reduce_sum(softmax_value, axis=1) 

print("Logits: \n",logit.numpy())
print("Probabilities : \n", softmax_value.numpy())
print("Sum of softmax values: \n", softmax_sum)  # sum = 1이여야함

Logits: 
 [[-1.916687   -5.733509    3.7484627  -7.279396   -4.2998385 ]
 [-9.271793    8.50437     1.3734322   8.120691    2.5568504 ]
 [-6.518402   -8.907463   -1.1298084  -9.354267   -3.547089  ]
 [-5.0065923   1.9698887  -2.3188806   8.167702    3.2706976 ]
 [ 2.5599842   0.04105759 -5.241158   -0.03053665 -1.3174458 ]
 [-3.8684416   6.427862   -5.7993507  -8.006101    4.8766327 ]
 [ 1.5249968  -1.7952442   0.8241539  -0.648551    1.1239719 ]
 [ 1.5017242   3.2117252   3.6775284  -4.457059   -6.321852  ]]
Probabilities : 
 [[3.4512498e-03 7.5919204e-05 9.9613827e-01 1.6180109e-05 3.1840993e-04]
 [1.1307632e-08 5.9355533e-01 4.7482588e-04 4.0441921e-01 1.5505522e-03]
 [4.1742632e-03 3.8284578e-04 9.1372675e-01 2.4489468e-04 8.1471302e-02]
 [1.8808609e-06 2.0146689e-03 2.7644903e-05 9.9055743e-01 7.3984000e-03]
 [8.4987754e-01 6.8454251e-02 3.4782704e-04 6.3724644e-02 1.7595837e-02]
 [2.7852233e-05 8.2506454e-01 4.0390278e-06 4.4452636e-07 1.7490311e-01]
 [4.3183157e-01 1.5608173e-02

##**Code3-4-2: Softmax in Dense Layers**##

In [ ]:
from os import access
import tensorflow as tf

from tensorflow.keras.layers import Dense

# 균등분포, 8 by 5 matrix
logit = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
# unit은 neuron의 갯수
dense = Dense(units=8, activation='softmax')

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[0.9999999  0.9999999  1.         1.         1.         0.99999994
 1.         1.        ], shape=(8,), dtype=float32)


#**3-5: Multi-class Classifiers**#

##**Code3-5-1: Multi-class Classifiers**##

In [3]:
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=8, activation='relu')
    self.dense2 = Dense(units=5, activation='relu')
    self.dense3 = Dense(units=3, activation='softmax')

  def call(self, x):
    print("X : {}\n{}\n".format(x.shape, x.numpy()))

    x = self.dense1(x)
    print("A1: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense2(x)
    print("A2: {}\n{}\n".format(x.shape, x.numpy()))
    
    x = self.dense3(x)
    print("Y: {}\n{}\n".format(x.shape, x.numpy()))
    print("Sum of vectors: {}\n".format(tf.reduce_sum(x, axis=1)))
    return x

model = TestModel()

X = tf.random.uniform(shape=(8, 5), minval = -10, maxval = 10)
Y = model(X)

X : (8, 5)
[[ 2.7306414  -4.5043635   9.202312   -9.729929    4.5601654 ]
 [-9.43515    -3.2731962   2.7073717  -1.8210602   6.039503  ]
 [-2.608459    9.926994   -3.7898111  -9.658632    8.525955  ]
 [-8.141861    7.6586723  -1.4186335  -7.7409053   7.511627  ]
 [ 7.6202927  -7.5814915   9.817312   -1.3243027  -8.664522  ]
 [ 5.2555637  -4.334736   -2.3588896   0.70489883  2.0085258 ]
 [ 4.0495033  -4.555273    7.438957    8.257582   -3.7457752 ]
 [ 1.2603779  -6.1622357  -9.3884735   7.5500984   3.566759  ]]

A1: (8, 8)
[[ 0.          0.          4.223045    0.          0.          2.1976156
   0.          0.        ]
 [ 4.4849157   0.          0.          3.895809    0.          6.2977552
   3.4857292   0.        ]
 [ 3.232225    0.          0.          0.          0.          0.
   6.2667346   0.        ]
 [ 6.5099583   0.          0.          3.0640934   0.          0.24818487
   8.033037    0.        ]
 [ 0.          0.         11.908857    0.          0.83686936  0.45559946
   0