<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH05_05_Conv2D_with_Filters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**5-2: Conv Layer with Filters**#

##**Code5-2-1: Shapes with Filters**##

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
# N = datasample의 갯수
N, n_H, n_W, n_C = 32, 28, 28, 3
# filter 1개당 output image 1장
n_filter = 5
# window size = k_size by k_size by n_C 
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

conv = Conv2D(filters=n_filter, kernel_size=k_size)

Y = conv(images)

W, B = conv.get_weights()
print("Input Image: {}".format(images.shape))
# W = 3 by 3 by 3이 5개, B = filter갯수
print("W/B : {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

Input Image: (32, 28, 28, 3)
W/B : (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 26, 5)


##**Code5-2-2: computations with Filters**##

In [10]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size)
Y = conv(images)
# print(Y.numpy().squeeze().shape)
# np.swapaxes() = 배열의 두 축 교환
# print(Y.numpy().squeeze().swapaxes(0,-1).shape)

# np.transpose() = 행렬의 축, 뱡향 바꿈
# shape(2, 2, 3) -> shape(3, 2, 2)
# n_C가 가장 앞으로 오도록
Y = np.transpose(Y.numpy().squeeze(),(2,0,1))

print("Y(Tensorflow): \n",Y)

W, B = conv.get_weights()

#Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  # weight의 갯수 = k_size by k_size by n_C by n_filter
  c_W = W[:, :, :, c]
  # bias의 갯수 = n_filter 
  c_B = B[c]

  # output의 n_H, n_B 사이즈 만큼
  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h + k_size, w:w + k_size,:]
      conv = np.sum(window * c_W) + c_B

      Y_man[h, w, c] = conv

print("Y(Manual): \n",np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[-0.15665042 -0.18671992]
  [ 0.48171073  0.10545997]]

 [[ 0.0552998   0.10727382]
  [-0.7468574  -0.13787341]]

 [[ 0.36121714  0.4150228 ]
  [ 0.07460253  0.6223297 ]]]
Y(Manual): 
 [[[-0.15665044 -0.18671983]
  [ 0.48171067  0.10545993]]

 [[ 0.05529979  0.10727387]
  [-0.74685729 -0.1378734 ]]

 [[ 0.36121711  0.41502282]
  [ 0.07460251  0.62232983]]]


In [12]:
# channel이 가장 앞에 오면 좀 더 다루기 쉬운 모양이 됨
import numpy as np

# 0~10 사이의 2 by 3 by 4 tensor
images = np.random.randint(low=0,high=10, size=(2,3,4))
print(images.shape)
for c in range(4):
  print(images[:,:,c])
print('\n')
# 차원 재배치
# channel(4)을 맨 앞으로 나머지(2,3)는 뒤로 밀림 -> (4,2,3)
images = np.transpose(images, (2, 0, 1))
for c in range(4):
  print(images[c, :, :])
print(images.shape)

# 처음의 images의 shape과 2,3번째 shape을 비교하면 transpose가 되어 channel이 가장 앞으로 온다.

(2, 3, 4)
[[2 5 0]
 [6 9 9]]
[[0 2 0]
 [7 0 9]]
[[2 1 4]
 [1 3 4]]
[[4 1 9]
 [5 7 6]]


[[2 5 0]
 [6 9 9]]
[[0 2 0]
 [7 0 9]]
[[2 1 4]
 [1 3 4]]
[[4 1 9]
 [5 7 6]]
(4, 2, 3)


#**5-3: Conv Layers with Activation Functions**#

##**5-3-1: Conv Layers with Activation Functions**##

In [15]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval=0, maxval=1, shape=(N, n_H, n_W, n_C))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters=n_filter, kernel_size=k_size, activation='sigmoid')
Y = conv(images)

# shape(2, 2, 3) -> shape(3, 2, 2)
# n_C가 가장 앞으로 오도록
Y = np.transpose(Y.numpy().squeeze(),(2,0,1))

print("Y(Tensorflow): \n",Y)

W, B = conv.get_weights()

#Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1, n_filter))
for c in range(n_filter):
  # weight의 갯수 = k_size by k_size by n_C by n_filter
  c_W = W[:, :, :, c]
  # bias의 갯수 = n_filter 
  c_B = B[c]

  # output의 n_H, n_B 사이즈 만큼
  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h + k_size, w:w + k_size,:]
      conv = np.sum(window * c_W) + c_B
      # activation = sigmoid
      conv = 1 / (1 + np.exp(-conv))

      Y_man[h, w, c] = conv

print("Y(Manual): \n",np.transpose(Y_man, (2, 0, 1)))

Y(Tensorflow): 
 [[[0.4381765  0.41805097]
  [0.5159454  0.41421336]]

 [[0.6743414  0.655199  ]
  [0.6629704  0.72552526]]

 [[0.40749657 0.3964018 ]
  [0.37281477 0.3364318 ]]]
Y(Manual): 
 [[[0.43817651 0.41805096]
  [0.51594537 0.41421336]]

 [[0.67434141 0.65519899]
  [0.66297043 0.72552526]]

 [[0.40749656 0.39640179]
  [0.37281474 0.33643177]]]
