<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH05_04_Conv2D_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**5-1: Conv Layers**##

##**Code5-1-1: Shapes of Conv Layers**##

In [11]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

# 4D tensor
# input image가 32장 들어옴
N, n_H, n_W, n_c = 32, 28, 28, 3
# neuron의 갯수
n_filter = 10
#kernel size
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_c)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
# 통과한 후에 kernel이 초기화됨

y = conv(images)

# W = kernel_size, B =  scalar 1개 
W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
# 28 - 3 + 1 = 26
print(y.shape)

(32, 28, 28, 3)
(3, 3, 3, 10)
(10,)
(32, 26, 26, 10)


##**Code5-1-2: Correlation Calculation**##

In [23]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_c = 1, 5, 5, 1
# neuron의 갯수
n_filter = 1
#kernel size
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_c)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
# 통과한 후에 kernel이 초기화됨

y = conv(images)
# squeeze() = 쓸모없는 dimension을 날려줌
print("Y(Tensorflow) : \n", y.numpy().squeeze())
W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
   # window extration
   window =  images[i : i+k_size, j : j+k_size]
   y_man[i,j] = np.sum(window*W) + B

print("Y(Manual): \n",y_man)

Y(Tensorflow) : 
 [[-0.71185434 -0.11861598 -0.5858892 ]
 [-0.6100012  -0.3226073  -0.62453073]
 [-0.682446   -0.16878973 -0.67579913]]
Y(Manual): 
 [[-0.71185434 -0.11861599 -0.58588922]
 [-0.61000121 -0.32260728 -0.62453073]
 [-0.682446   -0.16878974 -0.67579913]]


##**Code5-1-3: Correlation with n-channel**##

In [24]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_c = 1, 5, 5, 3
# neuron의 갯수
n_filter = 1
#kernel size
k_size = 3

images = tf.random.uniform(minval=0, maxval=1, shape=((N, n_H, n_W, n_c)))

conv = Conv2D(filters=n_filter, kernel_size=k_size)
# 통과한 후에 kernel이 초기화됨

y = conv(images)
# squeeze() = 쓸모없는 dimension을 날려줌
print("Y(Tensorflow) : \n", y.numpy().squeeze())
W, B = conv.get_weights()

####
images = images.numpy().squeeze()
W = W.squeeze()

y_man = np.zeros(shape=(n_H - k_size + 1, n_W - k_size + 1))
for i in range(n_H - k_size + 1):
  for j in range(n_W - k_size + 1):
   # window extration
   window =  images[i : i+k_size, j : j+k_size, :]
   y_man[i,j] = np.sum(window*W) + B

print("Y(Manual): \n",y_man)

Y(Tensorflow) : 
 [[-0.9191978  -0.60710543 -1.1420174 ]
 [-0.66887534 -0.5289647  -0.9036687 ]
 [-0.8995123  -0.27592507 -0.62456274]]
Y(Manual): 
 [[-0.91919774 -0.60710537 -1.14201736]
 [-0.66887534 -0.5289647  -0.9036687 ]
 [-0.89951235 -0.27592513 -0.62456274]]
