<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH06_03_Padding_and_Strides.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**6-3: 3D  Max/Avg Pooling**#

##**Code6-3-1: 3D MaxPooling**##

In [9]:
from re import S
#multi channel input
import math # gauss func
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2,2

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
#channel wise로 보기위해 transpose
# x.numpy().squeeze = (5, 5, 3)
# np.transpose(x.numpy().squeeze(), (2,0,1)) = (3, 5, 5)
print("x: {}\n{}".format(x.shape, np.transpose(x.numpy().squeeze(), (2,0,1))))
pool_max = MaxPooling2D(pool_size = f, strides = s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(),(2,0,1))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,pooled_max_t))

x = x.numpy().squeeze()
n_H_ = math.floor((n_H - f)/s + 1)
n_W_ = math.floor((n_W - f)/s + 1)
pooled_max_man = np.zeros(shape=(n_H_,n_W_,n_C))

# channel별로 들어옴
for c in range(n_C):
  c_image = x[:, :, c]

# input image의 index와 output image의 index가 달라 변수설정
  h_ = 0
  for h in range(0, n_H - f + 1, s):
    w_ = 0
    for w in range(0, n_W - f + 1, s):
      window = c_image[h:h+f, w:w+f]
      pooled_max_man[h_, w_, c] = np.max(window)

      w_ += 1
    h_ += 1 

pooled_max_t = np.transpose(pooled_max_man,(2,0,1))
print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,pooled_max_t))

x: (1, 5, 5, 3)
[[[-0.04165245 -0.69489294  0.2628172  -1.4416945   0.32234243]
  [-0.79485124 -1.2013087  -1.2264383   0.8739131  -0.7393973 ]
  [-0.8175927  -0.32816795 -0.712461   -1.6772014  -0.36527568]
  [-1.825489    1.2413286   0.14806442 -2.4312792  -0.9400049 ]
  [-0.5953234  -0.6701633   1.246382    0.0760054  -0.66434175]]

 [[ 0.69569916 -0.4265282   1.0689193  -2.368038   -2.049476  ]
  [ 0.3202273  -0.09945048  0.10267391  1.9018568  -0.40930164]
  [-0.332641    0.9687359  -0.5321431   1.397498   -2.3049204 ]
  [-0.8621706  -0.30300015 -0.02255699 -0.5857848   0.8662503 ]
  [ 0.01320763 -1.2768902   1.6485813   0.7326172  -0.6582798 ]]

 [[-0.44493952  0.9499523  -0.9830161   0.78371817 -0.88013387]
  [ 0.5741747  -0.5608523   0.11236259  0.20844218 -1.5184106 ]
  [ 0.05717982 -0.05508999  0.00551856  0.48005813 -0.87953824]
  [-1.1947052   0.86224306  0.17340192 -0.6662103   2.0635462 ]
  [-1.9396527   0.80733216 -0.391985   -0.8547198  -2.0354655 ]]]
pooled_max(Tensorf

#**6-4: Padding**#

##**Code6-4-1: Zero Padding 2D Layer**##

In [13]:
import tensorflow as tf

from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape=(1, 28, 28, 3))
print(images.shape)
# print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

zero_padding = ZeroPadding2D(padding=1)
y = zero_padding(images)

print(y.shape)
# print(np.transpose(y.numpy().squeeze(),(2, 0, 1)))


(1, 28, 28, 3)
(1, 30, 30, 3)


##**Code6-4-2: Zero Padding with COnv2D Layers**##

In [18]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
# padding = 'vaild' or 'same'
# same은  input shape = output shape 하도록 padding을 해줌 -> (f-1)/2 = padding size
conv = Conv2D(filters = 1, kernel_size = 3, padding='same')
y = conv(images)
print(y.shape)

(1, 28, 28, 1)


#**6-5: Strides**#

##**Code6-5-1: Strides in Conv2D Layers**##

In [20]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape=(1, 28, 28, 3))
# valid = no padding
conv = Conv2D(filters=1, kernel_size = 3, padding='valid',strides=2)
y = conv(images)

# n_H_ = [(n_H + 2p - f)/s + 1]
print(images.shape)
print(y.shape)

# conv layer는 filter의 갯수에 따라 channel의 수가 정해짐

(1, 28, 28, 3)
(1, 13, 13, 1)


##**Code6-5-2: Strides in Pooling Layers**##

In [22]:
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape=(1, 28, 28, 3))
pool = MaxPooling2D(pool_size = 3, strides =2)
y = pool(images)

# n_H_ = [(n_H + 2p - f)/s + 1]
print(images.shape)
print(y.shape)


(1, 28, 28, 3)
(1, 13, 13, 3)
