<a href="https://colab.research.google.com/github/Hiji1023/dl_network_cla_/blob/main/CH06_02_Max_and_Average_Pooling_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**6-1: Max/Avg Pooling**#

##**Code6-1-1: Max Pooling**##

In [8]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

L, f, s = 10, 2, 1

# input , shape= datasample의 갯수, length, channel
x = tf.random.normal(shape=(1, L, 1))
pool_max = MaxPooling1D(pool_size = f, strides = s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((L -f + 1, ))
for i in range(L -f +1):
  window = x[i:i+f]
  pooled_max_man[i] = np.max(window)

print("pooled_max(Manual: {}\n{}".format(pooled_max_man.shape, pooled_max_man))

x: (1, 10, 1)
[ 0.74785167  0.21461636  2.6922438   2.215315    1.1941749  -0.68907845
 -1.1156827  -0.09096188  0.19192913 -0.75345397]
pooled_max(Tensorflow): (1, 9, 1)
[ 0.74785167  2.6922438   2.6922438   2.215315    1.1941749  -0.68907845
 -0.09096188  0.19192913  0.19192913]
pooled_max(Manual: (9,)
[ 0.74785167  2.69224381  2.69224381  2.2153151   1.19417489 -0.68907845
 -0.09096188  0.19192913  0.19192913]


##**Code6-1-2: Average Pooling**##

In [10]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

L, f, s = 10, 2, 1

# input , shape= datasample의 갯수, length, channel
x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size = f, strides = s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((L -f + 1, ))
for i in range(L -f +1):
  window = x[i:i+f]
  pooled_avg_man [i] = np.mean(window)

print("pooled_max(Manual: {}\n{}".format(pooled_avg_man .shape, pooled_avg_man))

x: (1, 10, 1)
[-0.9663772  -1.9476278   0.38253033 -0.9386613  -0.223463    1.7386291
 -1.3975677  -1.4622998  -0.09377569 -0.6607355 ]
pooled_avg(Tensorflow): (1, 9, 1)
[-1.4570025  -0.7825487  -0.27806547 -0.58106214  0.757583    0.17053068
 -1.4299338  -0.7780378  -0.3772556 ]
pooled_max(Manual: (9,)
[-1.45700252 -0.78254873 -0.27806547 -0.58106214  0.75758302  0.17053068
 -1.42993379 -0.77803779 -0.37725559]


#**6-2: 2D Max/Avg Pooling**#

##**Code6-2-1: 2D Max Pooling**##

In [22]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
# pool =  f by f
pool_max = MaxPooling2D(pool_size=f, strides = s)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape, pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j] = np.max(window)

# output shape = (n_H-f+1, n_W-f+1)

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape, pooled_max_man))


x: (1, 5, 5, 1)
[[ 0.7827516  -0.30897748 -2.018037    1.1552018   0.7307982 ]
 [ 0.05400821  0.6710787   1.1512607   1.0191326   1.141896  ]
 [-0.56917226 -0.974233   -0.17592804  0.5750942   0.8271091 ]
 [ 0.32191488  0.00621981 -1.4048536   0.05103262 -0.10535239]
 [ 0.95224744 -0.37198898 -0.7996818   1.1455618  -1.4212846 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[0.7827516  1.1512607  1.1552018  1.1552018 ]
 [0.6710787  1.1512607  1.1512607  1.141896  ]
 [0.32191488 0.00621981 0.5750942  0.8271091 ]
 [0.95224744 0.00621981 1.1455618  1.1455618 ]]
pooled_max(Manual): (4, 4)
[[0.78275162 1.15126073 1.15520179 1.15520179]
 [0.67107868 1.15126073 1.15126073 1.14189601]
 [0.32191488 0.00621981 0.57509422 0.8271091 ]
 [0.95224744 0.00621981 1.14556181 1.14556181]]


##**Code6-2-2: 2D Average Pooling**##

In [23]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1
f, s = 2, 1

x = tf.random.normal(shape=(N, n_H, n_W, n_C))
# pool =  2 by 2
pool_avg = AveragePooling2D(pool_size=f, strides = s)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape, pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H - f + 1, n_W - f + 1))
for i in range(n_H - f + 1):
  for j in range(n_W - f + 1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j] = np.mean(window)

# output shape = (n_H-f+1, n_W-f+1)

print("pooled_max(Manual): {}\n{}".format(pooled_avg_man.shape, pooled_avg_man))

x: (1, 5, 5, 1)
[[ 0.26113737 -0.56307817  0.21443902 -0.19741607  0.9482374 ]
 [ 0.03316693 -0.3110888   0.19893058  0.98124266 -1.5929346 ]
 [-1.0411483   0.127162   -1.1271299   1.1738646   0.6369786 ]
 [-2.1159682  -0.7146053   0.11509072 -1.377871    0.7687496 ]
 [-0.2223623   1.1632506  -1.2287353  -1.425734   -0.01867203]]
pooled_avg(Tensorflow): (1, 4, 4, 1)
[[-0.14496566 -0.11519934  0.29929906  0.03478235]
 [-0.29797703 -0.27803153  0.306727    0.29978782]
 [-0.93613994 -0.3998706  -0.3040114   0.30043045]
 [-0.47242132 -0.16624983 -0.9793124  -0.51338184]]
pooled_max(Manual): (4, 4)
[[-0.14496566 -0.11519934  0.29929906  0.03478235]
 [-0.29797703 -0.27803153  0.30672699  0.29978782]
 [-0.93613994 -0.3998706  -0.3040114   0.30043045]
 [-0.47242132 -0.16624983 -0.97931242 -0.51338184]]
